config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope module: :web do
    root 'bulletins#index'
    post 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth

    resource :session, only: :destroy

    resources :bulletins, except: :destroy do
      member do
        patch :send_to_moderation
        patch :archive
      end
    end
    resource :profile, only: :show

    namespace :admin do
      root 'home#index'
      resources :bulletins, only: :index do
        member do
          patch :publish
          patch :reject
          patch :archive
        end
      end
      resources :categories, only: %i[index new create edit update destroy]
    end
  end
end

app/views/layouts/shared/_admin_panel.html.slim
.col-md-3
  ul.nav.nav-pills.flex-column.mb-auto
    li.nav-item
      = link_to t('.under_moderation'), admin_root_path,
              class: class_names('nav-link link-dark', { active: current_page?(admin_root_path) })
    li.nav-item
      = link_to t('.all_bulletins'), admin_bulletins_path,
              class: class_names('nav-link link-dark', { active: current_page?(admin_bulletins_path) })
    li.nav-item
      = link_to t('.all_categories'), admin_categories_path,
              class: class_names('nav-link link-dark', { active: current_page?(admin_categories_path) })

app/views/layouts/shared/_flash.html.slim
- if flash.any?
  .container.flex-shrink-0
    - flash.each do |type, msg|
      .alert class="#{flash_class(type)}" role="alert"
        == msg

app/views/layouts/shared/_footer.html.slim
.container
  footer.d-flex.flex-wrap.justify-content-between.align-items-center.py-3.my-4.border-top
    .col-md-4.d-flex.align-items-center
      span.mb-3.mb-md-0.text-muted
        = t('.hexlet_title', year: Time.zone.now.year)

app/views/layouts/shared/_nav.html.slim
.container.mb-2
  header.d-flex.flex-wrap.align-items-center.py-2.border-bottom
    .navbar.navbar-expand-md.navbar-light.me-auto
      = link_to t('.app_name'), root_path, class: 'navbar-brand me-md-4'
      #navbarToggler.collapse.navbar-collapse
        ul.nav.nav-pills.flex-grow-1.navbar-nav.me-auto
          li.nav-item.me-2
            = link_to t('.home_page'), root_path, class: 'nav-link text-dark'
          - if signed_in? && policy(Bulletin).new?
            li.nav-item.me-2
              = link_to t('.my_bulletins'), profile_path, class: 'nav-link text-dark'
            li.nav-item.me-2
              = link_to t('.add_bulletin'), new_bulletin_path, class: 'nav-link text-dark'
    ul.nav.nav-pills
      - if current_user&.admin?
        li.nav-item.me-2
          = link_to t('.admin'), admin_root_path, class: 'nav-link text-dark'
      - if signed_in?
        li.nav-item.me-2
          = link_to t('.sign_out'), session_path, method: :delete, class: 'nav-link text-dark'
      - else
        li.nav-item.me-2
          = link_to auth_request_path('github'), method: :post, class: 'btn btn-outline-dark' do
            span.bi.bi-github
              =< t('.sign_in')