config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope module: :web do
    root 'bulletins#index'
    post 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth

    resource :session, only: :destroy

    resources :bulletins, except: :destroy do
      member do
        patch :send_to_moderation
        patch :archive
      end
    end
    resource :profile, only: :show

    namespace :admin do
      root 'home#index'
      resources :bulletins, only: :index do
        member do
          patch :publish
          patch :reject
          patch :archive
        end
      end
      resources :categories, only: %i[index new create edit update destroy]
    end
  end
end

app/controllers/web/admin/home_controller.rb
# frozen_string_literal: true

class Web::Admin::HomeController < Web::Admin::ApplicationController
  def index
    @q = Bulletin.under_moderation.ransack(params[:q])
    @bulletins = @q.result.order(created_at: :desc).page(params[:page])
  end
end

app/views/web/admin/home/index.html.slim
- content_for :title do
  = t('.title')

h1.h2.mb-4 = t('.title')

.row.mt-2
  table.table.table-hover
    thead
      tr
        th{ scope: :col } = sort_link(@q, :title)
        th{ scope: :col } = sort_link(@q, :created_at)
        th{ scope: :col } = t('.actions')
    tbody
      - @bulletins.each do |bulletin|
        tr
          td
            = link_to bulletin.title, bulletin
          td = time_ago_in_words(bulletin.created_at)
          td
            - if bulletin.may_publish?
              = link_to t('.publish'), publish_admin_bulletin_path(bulletin),
                      method: :patch,
                      class: 'text-success me-1',
                      data: { confirm: t('.confirm_publication') }
            - if bulletin.may_reject?
              = link_to t('.reject'), reject_admin_bulletin_path(bulletin),
                      method: :patch,
                      class: 'me-1',
                      data: { confirm: t('.confirm_reject') }
            - if bulletin.may_archive?
              = link_to t('.archive'), archive_admin_bulletin_path(bulletin),
                      method: :patch,
                      class: 'text-danger',
                      data: { confirm: t('.confirm_archive') }
= paginate @bulletins, theme: 'bootstrap-5',
        pagination_class: 'pagination flex-wrap justify-content-center'