config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope module: :web do
    root 'bulletins#index'
    post 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth

    resource :session, only: :destroy

    resources :bulletins, except: :destroy do
      member do
        patch :send_to_moderation
        patch :archive
      end
    end
    resource :profile, only: :show

    namespace :admin do
      root 'home#index'
      resources :bulletins, only: :index do
        member do
          patch :publish
          patch :reject
          patch :archive
        end
      end
      resources :categories, only: %i[index new create edit update destroy]
    end
  end
end

app/controllers/web/profiles_controller.rb
# frozen_string_literal: true

class Web::ProfilesController < Web::ApplicationController
  before_action :authenticate_user!
  def show
    @q = current_user.bulletins.ransack(params[:q])
    @bulletins = @q.result.order(created_at: :desc).page(params[:page])
  end
end

app/views/web/profiles/_search_form.html.slim
.p-3.bg-light.border.shadow-sm.rounded-3
  = search_form_for @q, url: profile_path do |f|
    .row.my-2
      .col-6
        = f.input :title_cont, label: false, hint: :defaults
      .col-4
        = f.input :state_eq, as: :select,
                collection: Bulletin.aasm.states_for_select,
                label: false
      .col-2
        = f.submit t('search'), class: 'btn btn-primary me-2'
        = link_to t('reset'), url_for, class: 'btn btn-outline-primary'

app/views/web/profiles/show.html.slim
- content_for :title do
  = t('.title')

.mt-4.mb-5.pb-5
  .container
    .p-4.align-items-center.border.shadow.bg-white.rounded-3
      .row
        .p-3.p-lg-5.pt-lg-0
          .mb-4
            h2 = t('.title')
            hr
          = link_to t('.add_bulletin'), new_bulletin_path, class: 'btn btn-primary mb-3'
          = render 'search_form'
          .row.mt-2
            table.table.table-hover.mt-2
              thead
                tr
                  th{ scope: :col } = sort_link(@q, :title)
                  th{ scope: :col } = t('.state')
                  th{ scope: :col } = sort_link(@q, :created_at)
                  th{ scope: :col } = t('.actions')
                  th
              tbody
                - @bulletins.each do |bulletin|
                  tr
                    td = bulletin.title
                    td = bulletin.aasm.human_state
                    td = time_ago_in_words(bulletin.created_at)
                    td
                      = link_to t('.show'), bulletin_path(bulletin), class: 'me-2'
                      = link_to t('.edit'), edit_bulletin_path(bulletin), class: 'me-2'
                      - if bulletin.may_send_to_moderation?
                        = link_to t('.send_to_moderation'), send_to_moderation_bulletin_path(bulletin),
                                method: :patch,
                                class: 'me-2'
                      - if bulletin.may_archive?
                        = link_to t('.archive'), archive_bulletin_path(bulletin),
                                method: :patch,
                                data: { confirm: t('.confirm_archive') },
                                class: 'text-danger me-2'

= paginate @bulletins, theme: 'bootstrap-5',
        pagination_class: 'pagination flex-wrap justify-content-center'