config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope module: :web do
    root 'bulletins#index'
    post 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth

    resource :session, only: :destroy

    resources :bulletins, except: :destroy do
      member do
        patch :send_to_moderation
        patch :archive
      end
    end
    resource :profile, only: :show

    namespace :admin do
      root 'home#index'
      resources :bulletins, only: :index do
        member do
          patch :publish
          patch :reject
          patch :archive
        end
      end
      resources :categories, only: %i[index new create edit update destroy]
    end
  end
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :bulletins, dependent: :destroy, inverse_of: :category

  validates :name, presence: true
end

app/controllers/web/admin/categories_controller.rb
# frozen_string_literal: true

class Web::Admin::CategoriesController < Web::Admin::ApplicationController
  before_action :set_category, only: %i[edit update destroy]

  def index
    @categories = Category.all.page(params[:page])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      flash[:success] = t('.success')
      redirect_to admin_categories_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @category.update(category_params)
      flash[:success] = t('.success')
      redirect_to admin_categories_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @category.destroy
      flash[:success] = t('.success')
      redirect_to admin_categories_path
    else
      render :index, status: :unprocessable_entity
    end
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/views/web/admin/categories/_form.html.slim
= simple_form_for(category, url: url) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-floating
    = f.input :name, required: false
  .form-actions
    = f.button :submit, class: 'btn btn-success mt-4 btn-block'

app/views/web/admin/categories/edit.html.slim
= content_for :title do
  = t('.title')

.mt-4.mb-5.pb-5
  .container
    .p-4.align-items-center.border.shadow.bg-gradient.rounded-3
      .row
        .p-3.p-lg-5.pt-lg-0
          .mb-4
            h2 = t('.title')
            hr
          == render 'form', category: @category, url: admin_category_path(@category)

app/views/web/admin/categories/index.html.slim
- content_for :title do
  = t('.title')

h1.h2.mb-4 = t('activerecord.models.category.other')
= link_to t('.add_category'), new_admin_category_path, class: 'btn btn-primary'

.row.mt-2
  table.table.table-hover
    thead
      tr
        th{ scope: :col } = t('.id')
        th{ scope: :col } = t('.name')
        th{ scope: :col } = t('.actions')
    tbody
      - @categories.each do |category|
        tr
          td = category.id
          td = category.name
          td
            = link_to t('.edit'), edit_admin_category_path(category), class: 'me-1'
            = link_to t('.destroy'), admin_category_path(category),
                    method: :delete,
                    data: { confirm: t('.destroy_confirmation') },
                    class: 'me-1 text-danger'

  = paginate @categories, theme: 'bootstrap-5',
          pagination_class: 'pagination flex-wrap justify-content-center'

app/views/web/admin/categories/new.html.slim
= content_for :title do
  = t('.title')

.mt-4.mb-5.pb-5
  .container
    .p-4.align-items-center.border.shadow.bg-gradient.rounded-3
      .row
        .p-3.p-lg-5.pt-lg-0
          .mb-4
            h2 = t('.title')
            hr
          == render 'form', category: @category, url: admin_categories_path